params:
  secret_key: dev
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_DATABASE_URI: sqlite:///resources/database/data.db
  BOOTSTRAP_BTN_STYLE: primary
  BOOTSTRAP_BTN_SIZE: sm

user_profile:
  ALLOWED_EXTENSIONS:  {'png', 'jpg', 'jpeg'}
  UPLOAD_FOLDER: ./resources/user_profile/


db:
  type: sqlite
  db_path: ./resources/database/data.db
